import type { Product, Category, Review, Order } from '@/types'

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    slug: 'ankara',
    name: 'Ankara Prints',
    description: 'Traditional African print clothing with bold patterns and vibrant colors',
    image: 'https://picsum.photos/seed/ankara/800/600',
    sortOrder: 1,
  },
  {
    id: 'cat-2',
    slug: 'casual',
    name: 'Casual Wear',
    description: 'Everyday comfort with African-inspired flair',
    image: 'https://picsum.photos/seed/casual/800/600',
    sortOrder: 2,
  },
  {
    id: 'cat-3',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Complete your look with handcrafted accessories',
    image: 'https://picsum.photos/seed/accessories/800/600',
    sortOrder: 3,
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    slug: 'ankara-blazer-gold',
    name: 'Ankara Blazer - Gold Pattern',
    description: 'A stunning tailored blazer featuring traditional Ankara print in rich gold tones. Perfect for making a statement at any occasion. Crafted from premium African wax fabric with modern tailoring.',
    price: 285,
    comparePrice: 350,
    images: [
      'https://picsum.photos/seed/blazer1/800/1000',
      'https://picsum.photos/seed/blazer2/800/1000',
      'https://picsum.photos/seed/blazer3/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-1',
    category: mockCategories[0],
    variants: [
      { id: 'var-1', size: 'S', color: 'Gold', sku: 'ANK-BLZ-GLD-S', stock: 5, price: null },
      { id: 'var-2', size: 'M', color: 'Gold', sku: 'ANK-BLZ-GLD-M', stock: 8, price: null },
      { id: 'var-3', size: 'L', color: 'Gold', sku: 'ANK-BLZ-GLD-L', stock: 6, price: null },
      { id: 'var-4', size: 'XL', color: 'Gold', sku: 'ANK-BLZ-GLD-XL', stock: 4, price: null },
    ],
    averageRating: 4.5,
    reviewCount: 23,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    slug: 'ankara-midi-dress-indigo',
    name: 'Ankara Midi Dress - Indigo Wave',
    description: 'Elegant midi dress with flowing silhouette and bold Ankara indigo wave pattern. Features a flattering wrap design with adjustable waist tie.',
    price: 220,
    comparePrice: null,
    images: [
      'https://picsum.photos/seed/dress1/800/1000',
      'https://picsum.photos/seed/dress2/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-1',
    category: mockCategories[0],
    variants: [
      { id: 'var-5', size: 'S', color: 'Indigo', sku: 'ANK-DRS-IND-S', stock: 10, price: null },
      { id: 'var-6', size: 'M', color: 'Indigo', sku: 'ANK-DRS-IND-M', stock: 12, price: null },
      { id: 'var-7', size: 'L', color: 'Indigo', sku: 'ANK-DRS-IND-L', stock: 8, price: null },
      { id: 'var-8', size: 'XL', color: 'Indigo', sku: 'ANK-DRS-IND-XL', stock: 5, price: null },
    ],
    averageRating: 4.8,
    reviewCount: 31,
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-03-05T00:00:00Z',
  },
  {
    id: 'prod-3',
    slug: 'ankara-two-piece-crimson',
    name: 'Ankara Two-Piece Set - Crimson',
    description: 'Coordinated top and skirt set in stunning crimson Ankara print. The crop top features puff sleeves and the pencil skirt has a flattering high waist.',
    price: 320,
    comparePrice: 400,
    images: [
      'https://picsum.photos/seed/twopiece1/800/1000',
      'https://picsum.photos/seed/twopiece2/800/1000',
    ],
    isFeatured: false,
    status: 'published',
    categoryId: 'cat-1',
    category: mockCategories[0],
    variants: [
      { id: 'var-9', size: 'S', color: 'Crimson', sku: 'ANK-2PC-CRM-S', stock: 4, price: null },
      { id: 'var-10', size: 'M', color: 'Crimson', sku: 'ANK-2PC-CRM-M', stock: 6, price: null },
      { id: 'var-11', size: 'L', color: 'Crimson', sku: 'ANK-2PC-CRM-L', stock: 3, price: null },
    ],
    averageRating: 4.2,
    reviewCount: 8,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
  },
  {
    id: 'prod-4',
    slug: 'ankara-shirt-blue',
    name: 'Ankara Button-Down Shirt - Blue Kente',
    description: 'Modern button-down shirt with classic Kente-inspired pattern in blue tones. Relaxed fit, perfect for both casual and semi-formal occasions.',
    price: 180,
    comparePrice: null,
    images: [
      'https://picsum.photos/seed/shirt1/800/1000',
      'https://picsum.photos/seed/shirt2/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-1',
    category: mockCategories[0],
    variants: [
      { id: 'var-12', size: 'S', color: 'Blue', sku: 'ANK-SHT-BLU-S', stock: 7, price: null },
      { id: 'var-13', size: 'M', color: 'Blue', sku: 'ANK-SHT-BLU-M', stock: 10, price: null },
      { id: 'var-14', size: 'L', color: 'Blue', sku: 'ANK-SHT-BLU-L', stock: 9, price: null },
      { id: 'var-15', size: 'XL', color: 'Blue', sku: 'ANK-SHT-BLU-XL', stock: 5, price: null },
    ],
    averageRating: 4.6,
    reviewCount: 15,
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    id: 'prod-5',
    slug: 'heritage-hoodie-black',
    name: 'Heritage Hoodie - Black',
    description: 'Premium heavyweight hoodie with embroidered African heritage motif. Brushed fleece interior for ultimate comfort. Unisex fit.',
    price: 120,
    comparePrice: 150,
    images: [
      'https://picsum.photos/seed/hoodie1/800/1000',
      'https://picsum.photos/seed/hoodie2/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-2',
    category: mockCategories[1],
    variants: [
      { id: 'var-16', size: 'S', color: 'Black', sku: 'CAS-HOD-BLK-S', stock: 15, price: null },
      { id: 'var-17', size: 'M', color: 'Black', sku: 'CAS-HOD-BLK-M', stock: 20, price: null },
      { id: 'var-18', size: 'L', color: 'Black', sku: 'CAS-HOD-BLK-L', stock: 18, price: null },
      { id: 'var-19', size: 'XL', color: 'Black', sku: 'CAS-HOD-BLK-XL', stock: 10, price: null },
    ],
    averageRating: 4.7,
    reviewCount: 42,
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-03-08T00:00:00Z',
  },
  {
    id: 'prod-6',
    slug: 'adinkra-tee-white',
    name: 'Adinkra Symbol T-Shirt - White',
    description: 'Soft cotton tee featuring minimalist Adinkra symbol print. Relaxed unisex fit with rolled sleeves. Screen-printed with eco-friendly inks.',
    price: 85,
    comparePrice: null,
    images: [
      'https://picsum.photos/seed/tee1/800/1000',
      'https://picsum.photos/seed/tee2/800/1000',
    ],
    isFeatured: false,
    status: 'published',
    categoryId: 'cat-2',
    category: mockCategories[1],
    variants: [
      { id: 'var-20', size: 'S', color: 'White', sku: 'CAS-TEE-WHT-S', stock: 25, price: null },
      { id: 'var-21', size: 'M', color: 'White', sku: 'CAS-TEE-WHT-M', stock: 30, price: null },
      { id: 'var-22', size: 'L', color: 'White', sku: 'CAS-TEE-WHT-L', stock: 22, price: null },
      { id: 'var-23', size: 'XL', color: 'White', sku: 'CAS-TEE-WHT-XL', stock: 15, price: null },
    ],
    averageRating: 4.3,
    reviewCount: 18,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
  },
  {
    id: 'prod-7',
    slug: 'tribe-joggers-olive',
    name: 'Tribe Joggers - Olive',
    description: 'Premium joggers with subtle tribal pattern detail on the side seam. French terry cotton with tapered fit and elastic cuffs.',
    price: 95,
    comparePrice: null,
    images: [
      'https://picsum.photos/seed/joggers1/800/1000',
      'https://picsum.photos/seed/joggers2/800/1000',
    ],
    isFeatured: false,
    status: 'published',
    categoryId: 'cat-2',
    category: mockCategories[1],
    variants: [
      { id: 'var-24', size: 'S', color: 'Olive', sku: 'CAS-JOG-OLV-S', stock: 12, price: null },
      { id: 'var-25', size: 'M', color: 'Olive', sku: 'CAS-JOG-OLV-M', stock: 18, price: null },
      { id: 'var-26', size: 'L', color: 'Olive', sku: 'CAS-JOG-OLV-L', stock: 14, price: null },
      { id: 'var-27', size: 'XL', color: 'Olive', sku: 'CAS-JOG-OLV-XL', stock: 8, price: null },
    ],
    averageRating: 4.1,
    reviewCount: 12,
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'prod-8',
    slug: 'ankara-crossbody-bag',
    name: 'Ankara Crossbody Bag',
    description: 'Handcrafted crossbody bag with vibrant Ankara print exterior and vegan leather trim. Adjustable strap, zip closure, interior pocket.',
    price: 95,
    comparePrice: 120,
    images: [
      'https://picsum.photos/seed/bag1/800/1000',
      'https://picsum.photos/seed/bag2/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-3',
    category: mockCategories[2],
    variants: [
      { id: 'var-28', size: 'One Size', color: 'Multi', sku: 'ACC-BAG-MLT-OS', stock: 20, price: null },
    ],
    averageRating: 4.4,
    reviewCount: 9,
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z',
  },
  {
    id: 'prod-9',
    slug: 'gele-headwrap-emerald',
    name: 'Gelé Headwrap - Emerald',
    description: 'Luxurious traditional headwrap in rich emerald green. Made from premium Aso-Oke fabric, pre-shaped for easy styling. 72 inches long.',
    price: 65,
    comparePrice: null,
    images: [
      'https://picsum.photos/seed/headwrap1/800/1000',
      'https://picsum.photos/seed/headwrap2/800/1000',
    ],
    isFeatured: false,
    status: 'published',
    categoryId: 'cat-3',
    category: mockCategories[2],
    variants: [
      { id: 'var-29', size: 'One Size', color: 'Emerald', sku: 'ACC-HW-EMR-OS', stock: 30, price: null },
    ],
    averageRating: 4.9,
    reviewCount: 27,
    createdAt: '2026-02-12T00:00:00Z',
    updatedAt: '2026-03-22T00:00:00Z',
  },
  {
    id: 'prod-10',
    slug: 'beaded-statement-necklace',
    name: 'Beaded Statement Necklace - Coral & Gold',
    description: 'Handmade multi-strand beaded necklace inspired by traditional West African jewelry. Features coral, gold, and bone beads with brass clasp.',
    price: 145,
    comparePrice: 180,
    images: [
      'https://picsum.photos/seed/necklace1/800/1000',
      'https://picsum.photos/seed/necklace2/800/1000',
    ],
    isFeatured: true,
    status: 'published',
    categoryId: 'cat-3',
    category: mockCategories[2],
    variants: [
      { id: 'var-30', size: 'One Size', color: 'Coral/Gold', sku: 'ACC-NKL-CGL-OS', stock: 15, price: null },
    ],
    averageRating: 4.6,
    reviewCount: 14,
    createdAt: '2026-02-18T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },
]

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    rating: 5,
    title: 'Absolutely stunning!',
    body: 'The quality of the fabric is incredible. I wore it to a wedding and received so many compliments.',
    isVerified: true,
    userId: 'user-1',
    userName: 'Amara O.',
    productId: 'prod-1',
    createdAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'rev-2',
    rating: 4,
    title: 'Great fit',
    body: 'Fits true to size. The print is even more vibrant in person. Would love more color options.',
    isVerified: true,
    userId: 'user-2',
    userName: 'Kwame A.',
    productId: 'prod-1',
    createdAt: '2026-03-05T00:00:00Z',
  },
  {
    id: 'rev-3',
    rating: 5,
    title: 'My new favorite dress',
    body: 'The wrap design is so flattering. I have gotten so many compliments every time I wear it.',
    isVerified: true,
    userId: 'user-3',
    userName: 'Nneka C.',
    productId: 'prod-2',
    createdAt: '2026-03-10T00:00:00Z',
  },
  {
    id: 'rev-4',
    rating: 4,
    title: 'Best hoodie ever',
    body: 'Super comfortable and the embroidery is beautiful. Runs slightly large.',
    isVerified: true,
    userId: 'user-4',
    userName: 'David M.',
    productId: 'prod-5',
    createdAt: '2026-03-15T00:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ASA-2026-001',
    status: 'delivered',
    email: 'customer@example.com',
    subtotal: 505,
    discount: 75.75,
    shipping: 0,
    tax: 0,
    total: 429.25,
    currency: 'USD',
    stripePaymentId: 'pi_mock_123',
    paidAt: '2026-03-01T10:00:00Z',
    shippedAt: '2026-03-03T14:00:00Z',
    deliveredAt: '2026-03-08T09:00:00Z',
    trackingNumber: 'TRACK123456',
    trackingCarrier: 'DHL',
    notes: null,
    shippingAddress: {
      id: 'addr-1',
      name: 'John Doe',
      phone: '+1234567890',
      line1: '123 Main St',
      line2: 'Apt 4B',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'US',
    },
    items: [
      {
        id: 'oi-1',
        productName: 'Ankara Blazer - Gold Pattern',
        variantName: 'M / Gold',
        quantity: 1,
        unitPrice: 285,
        totalPrice: 285,
      },
      {
        id: 'oi-2',
        productName: 'Ankara Midi Dress - Indigo Wave',
        variantName: 'S / Indigo',
        quantity: 1,
        unitPrice: 220,
        totalPrice: 220,
      },
    ],
    createdAt: '2026-03-01T09:30:00Z',
    updatedAt: '2026-03-08T09:00:00Z',
  },
]

export const mockDashboardStats = {
  revenue: {
    today: 1250.00,
    thisWeek: 8540.00,
    thisMonth: 32150.00,
    growth: 12.5,
  },
  orders: {
    pending: 5,
    processing: 12,
    shipped: 45,
    total: 62,
  },
  inventory: {
    lowStock: 8,
    outOfStock: 2,
  },
  topProducts: [
    { id: 'prod-5', name: 'Heritage Hoodie - Black', sold: 45, revenue: 5400 },
    { id: 'prod-1', name: 'Ankara Blazer - Gold Pattern', sold: 38, revenue: 10830 },
    { id: 'prod-2', name: 'Ankara Midi Dress - Indigo Wave', sold: 31, revenue: 6820 },
    { id: 'prod-10', name: 'Beaded Statement Necklace', sold: 28, revenue: 4060 },
    { id: 'prod-6', name: 'Adinkra Symbol T-Shirt', sold: 25, revenue: 2125 },
  ],
  recentOrders: [
    { id: 'order-1', orderNumber: 'ASA-2026-001', customer: 'John Doe', total: 429.25, status: 'delivered' as const, createdAt: '2026-03-08T09:00:00Z' },
    { id: 'order-2', orderNumber: 'ASA-2026-002', customer: 'Jane Smith', total: 220.00, status: 'shipped' as const, createdAt: '2026-03-10T14:30:00Z' },
    { id: 'order-3', orderNumber: 'ASA-2026-003', customer: 'Mike Johnson', total: 180.00, status: 'processing' as const, createdAt: '2026-03-12T11:00:00Z' },
    { id: 'order-4', orderNumber: 'ASA-2026-004', customer: 'Sarah Williams', total: 350.00, status: 'paid' as const, createdAt: '2026-03-15T16:45:00Z' },
    { id: 'order-5', orderNumber: 'ASA-2026-005', customer: 'Chris Brown', total: 95.00, status: 'pending' as const, createdAt: '2026-03-18T08:20:00Z' },
  ],
}
